INSERT INTO manufacturer (name)
VALUES
    ("Abarth"),
    ("Aiways"),
    ("Alfa Romeo"),
    ("Alpine"),
    ("Asia Motors"),
    ("Aston Martin"),
    ("Audi"),
    ("Austin"),
    ("Autobianchi"),
    ("Bentley"),
    ("BMW"),
    ("Bugatti"),
    ("Buick"),
    ("Cadillac"),
    ("Carver"),
    ("Chevrolet"),
    ("Chrysler"),
    ("Citroen"),
    ("Corvette"),
    ("Cupra"),
    ("Dacia"),
    ("Daewoo"),
    ("Daihatsu"),
    ("Daimler"),
    ("Datsun"),
    ("Dodge"),
    ("Donkervoort"),
    ("DS"),
    ("Ferrari"),
    ("Fiat"),
    ("Fisker"),
    ("Ford"),
    ("FSO"),
    ("Galloper"),
    ("Honda"),
    ("Hummer"),
    ("Hyundai"),
    ("Infiniti"),
    ("Innocenti"),
    ("Iveco"),
    ("Jaguar"),
    ("Jeep"),
    ("Josse"),
    ("Kia"),
    ("Lada"),
    ("Lamborghini"),
    ("Lancia"),
    ("Land Rover"),
    ("Landwind"),
    ("Lexus"),
    ("Lincoln"),
    ("Lotus"),
    ("Marcos"),
    ("Maserati"),
    ("Maybach"),
    ("Mazda"),
    ("McLaren"),
    ("Mega"),
    ("Mercedes-Benz"),
    ("Mercury"),
    ("MG"),
    ("Mini"),
    ("Mitsubishi"),
    ("Morgan"),
    ("Morris"),
    ("Nissan"),
    ("Noble"),
    ("Opel"),
    ("Peugeot"),
    ("PGO"),
    ("Polestar"),
    ("Pontiac"),
    ("Porsche"),
    ("Princess"),
    ("Renault"),
    ("Rolls-Royce"),
    ("Rover"),
    ("Saab"),
    ("Seat"),
    ("Skoda"),
    ("Smart"),
    ("Spectre"),
    ("Ssangyong"),
    ("Subaru"),
    ("Suzuki"),
    ("Talbot"),
    ("Tesla"),
    ("Think"),
    ("Toyota"),
    ("Triumph"),
    ("TVR"),
    ("Volkswagen"),
    ("Volvo"),
    ("Yugo");

INSERT INTO car_body (type)
VALUES
    ("SUV"),
    ("Convertible"),
    ("Coupe"),
    ("Hatchback"),
    ("Sedan"),
    ("Station wagon"),
    ("Minivan"),
    ("MPV"),
    ("Diesel"),
    ("Hybrid/Electric"),
    ("Luxury");

INSERT INTO fuel (type)
VALUES
    ("Petrol"),
    ("Diesel"),
    ("Petrol + Gas (LPG)"),
    ("Petrol + Methane (CNG)"),
    ("Electric"),
    ("Hybrid");